### PR TITLE
Remove hook to deleted_plugin as de declared class method does not exist in Jetpack_Beta

### PR DESCRIPTION
**Pull request by oskosk**
When deleting a plugin a could see this logged into debug.log

```
call_user_func_array() expects parameter 1 to be a valid callback, class 'Jetpack_Beta' does not have a method 'deleted_plugin'
```

and indeed, the method does not exist there even though we try to hook it.

### CODE REVIEW

**Comment by oskosk** [comment]
@enejb do you think it's fine to delete this line? Or was there any planned behaviour to do on `deleted_plugin` that we should introduce as a method?

**Comment by enejb** [comment]
I think it is fine. I think we should delete the plugin settings if the user deleted the plugin. 
So might be easy to add them as well. 

All we need is the following. 
static function deleted_plugin() {
delete_option( self::$option_dev_installed );
delete_option( self::$option );
delete_option(  'jp_beta_autoupdate' );
}

**Comment by oskosk** [comment]
`deleted_plugin` is run after the plugin is deleted so the hook won't work here;

The deactivate hook is probably helping as the only way to delete the plugin and don't go through deactivation is by means of the wp cli.

**Comment by oskosk** [comment]
Ahh I can check if hooking on `delete_plugin` works instead.

**Comment by oskosk** [comment]
hrm... Hooking on `delete_plugin` means we're gonna delete stuff that the plugin needs before we know for sure that it can be deleted successfully

**Comment by oskosk** [comment]
Alright, I'm merging this one and then implementing  #45

**Comment by enejb** [comment]
❤️

**Pull request merged**
